/*
 * ⚠️  KAYAN-REPLICATE-ISOLATION-V1
 * LEGACY — REPLICATE-BASED, NOT PRODUCTION.
 *
 * This script references Replicate API. It must NEVER be used as
 * evidence that production video was generated by Replicate.
 *
 * Official production video pipeline:
 *   POST /api/video/generate
 *     → productionEngine.createProductionJob('VIDEO_GEN')
 *     → kayanGpuProvider.generateVideoKayanGpu()
 *     → GpuQueueService.enqueue('VIDEO_JOB')  [PostgreSQL]
 *     → queue-worker → KayanGPU Worker /jobs/video
 *     → LightX2V + HunyuanVideo 1.5 FP8 (A10G)
 *     → real MP4
 */
if (process.env.NODE_ENV === "production" && process.env.KAYAN_ALLOW_LEGACY_TESTS !== "1") { throw new Error("KAYAN-REPLICATE-ISOLATION-V1: this Replicate-based legacy script is blocked in production. Production video pipeline is KayanGPU only."); }

import fs from "node:fs";
import path from "node:path";

function loadEnvFile() {
  const env = {};
  const envPaths = [".env", "/home/ubuntu/Nashash/.env"];
  for (const p of envPaths) {
    if (fs.existsSync(p)) {
      const content = fs.readFileSync(p, "utf-8");
      content.split("\n").forEach((line) => {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith("#") && trimmed.includes("=")) {
          const idx = trimmed.indexOf("=");
          const k = trimmed.substring(0, idx).trim();
          let v = trimmed.substring(idx + 1).trim();
          if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
            v = v.slice(1, -1);
          }
          env[k] = v;
        }
      });
      break;
    }
  }
  return env;
}

async function runCheck() {
  console.log("\n=======================================================");
  console.log("🔍 فحص مفاتيح الذكاء الاصطناعي في السيرفر (.env):");
  console.log("=======================================================");

  const env = loadEnvFile();

  const deepgramKey = env.DEEPGRAM_API_KEY || process.env.DEEPGRAM_API_KEY;
  const replicateToken = env.REPLICATE_API_TOKEN || process.env.REPLICATE_API_TOKEN;
  const replicateVideoModel = env.REPLICATE_VIDEO_MODEL_VERSION || process.env.REPLICATE_VIDEO_MODEL_VERSION;
  const replicateLipModel = env.REPLICATE_LIPSYNC_MODEL_VERSION || process.env.REPLICATE_LIPSYNC_MODEL_VERSION;
  const groqKey = env.GROQ_API_KEY || process.env.GROQ_API_KEY;

  console.log("1. DEEPGRAM_API_KEY (توليد الصوت الحقيقي):", deepgramKey ? `✅ مفعل (${deepgramKey.slice(0, 4)}****)` : "❌ مفقود أو غير معرف");
  console.log("2. REPLICATE_API_TOKEN (توليد لقطات الفيديو):", replicateToken ? `✅ مفعل (${replicateToken.slice(0, 4)}****)` : "❌ مفقود أو غير معرف");
  console.log("3. REPLICATE_VIDEO_MODEL_VERSION (موديل الفيديو):", replicateVideoModel ? `✅ مفعل (${replicateVideoModel.slice(0, 8)}...)` : "❌ مفقود أو غير معرف");
  console.log("4. REPLICATE_LIPSYNC_MODEL_VERSION (حركة الشفاه):", replicateLipModel ? `✅ مفعل (${replicateLipModel.slice(0, 8)}...)` : "❌ مفقود أو غير معرف");
  console.log("5. GROQ_API_KEY (توليد السكربت والترجمة):", groqKey ? `✅ مفعل (${groqKey.slice(0, 4)}****)` : "❌ مفقود أو غير معرف");

  console.log("=======================================================\n");

  if (deepgramKey) {
    console.log("⏳ اختبار الاتصال الحقيقي بـ Deepgram Audio API...");
    try {
      const res = await fetch("https://api.deepgram.com/v1/speak?model=aura-asteria-en", {
        method: "POST",
        headers: { Authorization: `Token ${deepgramKey}`, "Content-Type": "application/json" },
        body: JSON.stringify({ text: "Testing Kayan Audio Connection" })
      });
      if (res.ok) {
        console.log("   ✅ حساب Deepgram يعمل بنجاح ورصيده نشط ومصرح له بالتوليد!");
      } else {
        console.log(`   ⚠️ Deepgram رفض الاتصال (HTTP ${res.status}):`, await res.text());
      }
    } catch (e) {
      console.log("   ❌ فشل الاتصال:", e.message);
    }
  }

  if (replicateToken) {
    console.log("\n⏳ اختبار الاتصال الحقيقي بـ Replicate Video API...");
    try {
      const res = await fetch("https://api.replicate.com/v1/predictions", {
        method: "GET",
        headers: { Authorization: `Bearer ${replicateToken}` }
      });
      if (res.ok) {
        console.log("   ✅ حساب Replicate يعمل بنجاح والـ Token صالح 100%!");
      } else {
        console.log(`   ⚠️ Replicate رفض الاتصال (HTTP ${res.status}):`, await res.text());
      }
    } catch (e) {
      console.log("   ❌ فشل الاتصال بـ Replicate:", e.message);
    }
  }

  process.exit(0);
}

runCheck().catch(console.error);
