import pg from "pg";
import fs from "fs";
import path from "path";

const { Pool } = pg;

function getDbUrl() {
  if (process.env.DATABASE_URL && process.env.DATABASE_URL.trim()) {
    return process.env.DATABASE_URL;
  }
  const envPaths = [".env", "../../.env", "/home/ubuntu/Nashash/.env"];
  for (const p of envPaths) {
    if (fs.existsSync(p)) {
      const content = fs.readFileSync(p, "utf-8");
      const match = content.match(/DATABASE_URL=["']?([^"'\n\r]+)["']?/);
      if (match && match[1]) return match[1];
    }
  }
  return process.env.DATABASE_URL || "";
}

const pool = new Pool({ connectionString: getDbUrl() });

const actorsList = [
  {
    id: 1,
    name: "طارق المنصور",
    type: "عربي / خليجي",
    category: "drama",
    age: 38,
    style: "قيادي، حازم، نبرة صوت عميقة، كاريزما سينمائية قوية",
    gender: "ذكر",
    role: "بطل رئيسي / قائد استراتيجي",
    personality: "هادئ، ذكي، صارم في قراراته، يمتلك بعد نظر استراتيجي",
    appearance: JSON.stringify({ face: "ملامح عربية حادة، لحية مشذبة", eyes: "بنية داكنة", hair: "أسود قصير", bodyBuild: "رياضي متناسق" }),
    wardrobe: JSON.stringify({ defaultClothing: "بدلة رسمية داكنة فاخرة", colors: "كحلي، رمادي داكن، أسود" }),
    character_prompt: "Cinematic portrait of Tariq Al-Mansoor, 38-year-old Arab leader, sharp features, tailored charcoal suit, 8k photorealistic",
  },
  {
    id: 2,
    name: "سارة الأحمد",
    type: "عربي / شامي",
    category: "contemporary",
    age: 31,
    style: "واثقة، سريعة البديهة، أسلوب قانوني واستقصائي راقٍ",
    gender: "أنثى",
    role: "بطلة رئيسية / محامية وصحفية",
    personality: "شجاعة، فضولية، تبحث عن الحقيقة وتواجه التحديات",
    appearance: JSON.stringify({ face: "ملامح ناعمة واثقة", eyes: "عسلية", hair: "كستنائي مموج", bodyBuild: "رشيقة وأنيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة بليزر عصرية وقميص أبيض", colors: "عاجي، كحلي، عنابي" }),
    character_prompt: "Cinematic portrait of Sarah Al-Ahmad, 31-year-old Arab woman lawyer, hazel eyes, navy blazer, intelligent expression",
  },
  {
    id: 3,
    name: "يوسف النجار",
    type: "عربي / مصري",
    category: "noir",
    age: 44,
    style: "محقق جنائي غامض، عميق التفكير، نبرة هادئة وساخرة",
    gender: "ذكر",
    role: "محقق جنائي / خبير غموض",
    personality: "ملاحظ دقيق للتفاصيل، لا يثق بسهولة",
    appearance: JSON.stringify({ face: "ملامح ناضجة تحمل تجارب السنين", eyes: "سوداء ثاقبة", hair: "أسود يتخلله شيب", bodyBuild: "طويل القامة" }),
    wardrobe: JSON.stringify({ defaultClothing: "معطف جلدي طويل وقبعة فيدورا", colors: "بني محروق، رمادي دخاني" }),
    character_prompt: "Cinematic film-noir still of Yousef Al-Najjar, 44-year-old detective, trench coat, foggy alleyway lighting",
  },
  {
    id: 4,
    name: "ليلى الشامي",
    type: "عربي / شامي",
    category: "scifi",
    age: 28,
    style: "عالمة ذكاء اصطناعي وباحثة مستقبلية",
    gender: "أنثى",
    role: "عالمة ومخترعة / خيال علمي",
    personality: "منهجية، دقيقة، تسعى لحل ألغاز التكنولوجيا",
    appearance: JSON.stringify({ face: "بشرة نضرة، ملامح معاصرة", eyes: "خضراء مائلة للعسلي", hair: "أسود قصير", bodyBuild: "رياضية" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة تقنية بألياف نيون", colors: "فضي معدني، أزرق نيون" }),
    character_prompt: "Portrait of Layla Al-Shami, 28-year-old tech scientist, glowing cyber accents, short hair, sci-fi lab background",
  },
  {
    id: 5,
    name: "خالد العمري",
    type: "عربي / تاريخي",
    category: "history",
    age: 42,
    style: "فارس وقائد تاريخي، شجاعة وصوت جهوري",
    gender: "ذكر",
    role: "قائد فرسان / تاريخي وملحمي",
    personality: "نبيل، مخلص لعهده، حازم في المعارك",
    appearance: JSON.stringify({ face: "بشرة سمراء، عيون صقرية، لحية كاملة", eyes: "بنية", hair: "طويل للخلف", bodyBuild: "بنية عضلية فارعة" }),
    wardrobe: JSON.stringify({ defaultClothing: "درع جلدي مزخرف بالنحاس", colors: "ترابي، برونزي، أحمر داكن" }),
    character_prompt: "Cinematic epic shot of Khalid Al-Omari, 42-year-old ancient Arab warrior, armor, fierce determined gaze, golden hour desert lighting",
  },
  {
    id: 6,
    name: "مريم القحطاني",
    type: "عربي / خليجي",
    category: "history",
    age: 29,
    style: "عالمة آثار ومستكشفة حضارات قديمة",
    gender: "أنثى",
    role: "مستكشفة ومؤرخة / مغامرات",
    personality: "عاشقة للتراث والتاريخ، جريئة في الميدان",
    appearance: JSON.stringify({ face: "ملامح أصيلة، ابتسامة واثقة", eyes: "بنية واسعة", hair: "مضفور", bodyBuild: "رياضية ميدانية" }),
    wardrobe: JSON.stringify({ defaultClothing: "زي استكشاف صحراوي مع وشاح كتان", colors: "كاكي، بيج، بني" }),
    character_prompt: "Cinematic portrait of Maryam Al-Qahtani, 29-year-old archaeologist explorer in desert ruins, adventure film aesthetic",
  },
  {
    id: 7,
    name: "كريم عبد الله",
    type: "عربي / مصري",
    category: "advertising",
    age: 26,
    style: "شاب عصري حيوي ومقنع، كاريزما إعلانية وتجارية",
    gender: "ذكر",
    role: "واجهة إعلانية / ريادي أعمال",
    personality: "مرح، متفائل، متحدث لبق",
    appearance: JSON.stringify({ face: "ملامح وسيمة وشابة", eyes: "عسلية", hair: "بني مموج", bodyBuild: "رشيق" }),
    wardrobe: JSON.stringify({ defaultClothing: "تيشيرت عصري وقميص كتان مفتوح", colors: "أبيض، كحلي، زيتوني" }),
    character_prompt: "Commercial portrait of Kareem Abdullah, 26-year-old charismatic Arab entrepreneur, radiant smile, studio commercial lighting",
  },
  {
    id: 8,
    name: "نورا الزهراني",
    type: "عربي / خليجي",
    category: "drama",
    age: 35,
    style: "سيدة أعمال ومفاوضة دبلوماسية رفيعة المستوى",
    gender: "أنثى",
    role: "شخصية نافذة / دراما اجتماعية",
    personality: "هادئة، حكيمة، تمتلك مهارات قيادية",
    appearance: JSON.stringify({ face: "ملامح ملكية راقية", eyes: "بنية داكنة", hair: "أسود ناعم", bodyBuild: "قوام ممشوق" }),
    wardrobe: JSON.stringify({ defaultClothing: "عباءة مخملية مطرزة بالحرير", colors: "زمردي، أسود، ذهبي" }),
    character_prompt: "Cinematic portrait of Noura Al-Zahrani, 35-year-old elegant Arab businesswoman, emerald couture abaya, luxury cinematic lighting",
  },
  {
    id: 9,
    name: "زياد الشريف",
    type: "عربي / شامي",
    category: "noir",
    age: 33,
    style: "عميل استخباراتي وطيار سابق، سريع الحركة",
    gender: "ذكر",
    role: "بطل أكشن / تشويق وجريمة",
    personality: "صارم، قليل الكلام، ينفذ المهام بدقة",
    appearance: JSON.stringify({ face: "فكان بارزان، نظرة حادة", eyes: "رمادية مائلة للبني", hair: "قصير عسكري", bodyBuild: "قتالي قوي" }),
    wardrobe: JSON.stringify({ defaultClothing: "جاكيت بومبر جلدي تكتيكي", colors: "أسود كربوني، رمادي خرساني" }),
    character_prompt: "Cinematic action shot of Ziad Al-Sharif, 33-year-old operative, tactical jacket, rain and city lights bokeh background",
  },
  {
    id: 10,
    name: "ريم البلوشي",
    type: "عربي / خليجي",
    category: "contemporary",
    age: 27,
    style: "صحفية استقصائية جريئة ومقدمة بودكاست وثائقي",
    gender: "أنثى",
    role: "إعلامية وباحثة / دراما ومعاصر",
    personality: "عنيدة في ملاحقة الحقيقة، ذكية",
    appearance: JSON.stringify({ face: "ملامح شبابية معبرة", eyes: "بنية لامعة", hair: "أسود متوسط", bodyBuild: "رشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة جينز وسماعات احترافية", colors: "كحلي، خردلي، أبيض" }),
    character_prompt: "Cinematic documentary still of Reem Al-Balushi, 27-year-old investigative journalist, urban background, realistic lighting",
  },
  {
    id: 11,
    name: "ماجد التميمي",
    type: "عربي / خليجي",
    category: "scifi",
    age: 36,
    style: "قائد محطة فضاء ومستكشف عوالم جديدة",
    gender: "ذكر",
    role: "قائد فضاء / خيال علمي",
    personality: "منضبط، شجاع، يتخذ قرارات حاسمة",
    appearance: JSON.stringify({ face: "ملامح صارمة هادئة", eyes: "عسلية داكنة", hair: "أسود قصير جداً", bodyBuild: "قوي متمرس" }),
    wardrobe: JSON.stringify({ defaultClothing: "بذلة رواد فضاء بيضاء بشارات عربية", colors: "أبيض ناصع، رمادي" }),
    character_prompt: "Cinematic space movie still of Majed Al-Tamimi, 36-year-old Arab astronaut commander in high-tech spacesuit, Interstellar aesthetic",
  },
  {
    id: 12,
    name: "فاطمة الدوسري",
    type: "عربي / خليجي",
    category: "drama",
    age: 40,
    style: "طبيبة جراحة ورئيسة قسم طبي إنساني",
    gender: "أنثى",
    role: "طبيبة وقيادية / دراما إنسانية",
    personality: "حنونة، مخلصة لمهنتها، قوية تحت الضغط",
    appearance: JSON.stringify({ face: "ملامح مريحة تبعث على الاطمئنان", eyes: "بنية دافئة", hair: "مغطى بغطاء طبي", bodyBuild: "معتدلة" }),
    wardrobe: JSON.stringify({ defaultClothing: "معطف طبي أبيض فوق ملابس العمليات", colors: "أبيض، أزرق سماوي" }),
    character_prompt: "Hospital drama portrait of Dr. Fatima Al-Dosari, 40-year-old surgeon, stethoscope around neck, warm compassionate gaze",
  },
  {
    id: 13,
    name: "حمزة إدريس",
    type: "عربي / مغاربي",
    category: "advertising",
    age: 25,
    style: "بطل رياضي ومدرب لياقة، طاقة إيجابية",
    gender: "ذكر",
    role: "رياضي وواجهة تسويقية / إعلانات",
    personality: "ملهم، نشيط، يتحدى الصعاب",
    appearance: JSON.stringify({ face: "ملامح رياضية منحوتة", eyes: "بنية", hair: "مجعد قصير", bodyBuild: "عضلات مفتولة" }),
    wardrobe: JSON.stringify({ defaultClothing: "ملابس رياضية تقنية حديثة", colors: "أسود، برتقالي ناري" }),
    character_prompt: "High-energy commercial shot of Hamza Idriss, 25-year-old Arab athlete running in modern city, sunrise lighting",
  },
  {
    id: 14,
    name: "هدى السعيد",
    type: "عربي / شامي",
    category: "drama",
    age: 48,
    style: "دبلوماسية وأستاذة علاقات دولية، وقار وحكمة",
    gender: "أنثى",
    role: "سفيرة ودبلوماسية / دراما سياسية",
    personality: "دقيقة، بارعة في التفاوض وحل النزاعات",
    appearance: JSON.stringify({ face: "وقار ونضج، نظارات طبية بإطار ذهبي", eyes: "عسلية داكنة", hair: "فضي منسق", bodyBuild: "أنيقة ورزينة" }),
    wardrobe: JSON.stringify({ defaultClothing: "بدلة رسمية كلاسيكية مع وشاح حريري", colors: "كحلي ملكي، عنابي" }),
    character_prompt: "Portrait of Huda Al-Saeed, 48-year-old seasoned diplomat, tailored dark royal blue suit, international summit background",
  },
  {
    id: 15,
    name: "بدر المطيري",
    type: "عربي / خليجي",
    category: "history",
    age: 50,
    style: "نوخذة وقبطان بحري تراثي، خبير بالنجوم",
    gender: "ذكر",
    role: "قبطان ومستكشف بحري / تاريخي وتراثي",
    personality: "حكيم، صبور، يحفظ خرائط البحار",
    appearance: JSON.stringify({ face: "تجاعيد وقورة، لحية بيضاء", eyes: "بنية عميقة", hair: "أبيض", bodyBuild: "قوي متمرس" }),
    wardrobe: JSON.stringify({ defaultClothing: "دشداشة تقليدية وغترة بيضاء", colors: "أبيض، بيج رملي" }),
    character_prompt: "Cinematic portrait of Captain Bader Al-Mutairi, 50-year-old Arab sea captain on traditional wooden ship, sea breeze, sunset",
  },
  {
    id: 16,
    name: "شهد العتيبي",
    type: "عربي / خليجي",
    category: "contemporary",
    age: 24,
    style: "مهندسة معمارية شابة ورائدة في الاستدامة",
    gender: "أنثى",
    role: "مهندسة ومصممة / معاصر وإعلانات",
    personality: "مبتكرة، طموحة، تجمع الأصالة والحداثة",
    appearance: JSON.stringify({ face: "ابتسامة ملهمة وملامح ذكية", eyes: "سوداء واسعة", hair: "أسود ناعم", bodyBuild: "رشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "خوذة مهندس بيضاء مع مخططات هندسية", colors: "أبيض، رمادي فاتح" }),
    character_prompt: "Cinematic shot of Shahad Al-Otaibi, 24-year-old female architect holding blueprint overlooking modern skyline, morning light",
  },
  {
    id: 17,
    name: "سامي حداد",
    type: "عربي / شامي",
    category: "noir",
    age: 39,
    style: "خبير أدلة جنائية وتحليل مسرح الجريمة",
    gender: "ذكر",
    role: "محلل جنائي / غموض وتحقيق",
    personality: "مهووس بالحقائق العلمية الدقيقة",
    appearance: JSON.stringify({ face: "ملامح مركزة، نظارات بدون إطار", eyes: "بنية فاتحة", hair: "بني قصير", bodyBuild: "نحيل" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة مختبر رمادية وقفازات فحص", colors: "رمادي، كحلي" }),
    character_prompt: "Forensic investigator Sami Haddad analyzing glowing evidence in dark forensics lab, blue ultraviolet lighting",
  },
  {
    id: 18,
    name: "دانة العلي",
    type: "عربي / خليجي",
    category: "advertising",
    age: 29,
    style: "مقدمة برامج تلفزيونية وإعلامية متألقة",
    gender: "أنثى",
    role: "مذيعة وإعلامية / دعاية وإعلام",
    personality: "فصيحة، لبقة، تمتلك حضوراً طاغياً",
    appearance: JSON.stringify({ face: "ملامح إعلامية جذابة ومشرقة", eyes: "عسلية براقة", hair: "كستنائي مموج", bodyBuild: "أنيقة جداً" }),
    wardrobe: JSON.stringify({ defaultClothing: "فستان رسمي راقٍ للمؤتمرات", colors: "أزرق نيلي، وردي هادئ" }),
    character_prompt: "Studio portrait of Dana Al-Ali, 29-year-old TV anchorwoman, holding microphone, professional broadcast studio lights",
  },
  {
    id: 19,
    name: "وليد الصبان",
    type: "عربي / مغاربي",
    category: "history",
    age: 62,
    style: "حكيم القرية وراوي الأساطير الشعبية",
    gender: "ذكر",
    role: "حكيم وراوٍ / قصص وروايات وفانتازيا",
    personality: "هادئ، صوته رخيم يأسر الألباب",
    appearance: JSON.stringify({ face: "وجه منير ممتلئ بالحكمة، لحية بيضاء", eyes: "بنية حنونة", hair: "أبيض كامل", bodyBuild: "مهيب" }),
    wardrobe: JSON.stringify({ defaultClothing: "قفطان مغربي أصيل وعمامة", colors: "أبيض عاجي، بيج صوفي" }),
    character_prompt: "Cinematic portrait of Walid Al-Sabban, 62-year-old wise storyteller around fireplace, warm amber glow, Arabian Nights aesthetic",
  },
  {
    id: 20,
    name: "دينا المغربي",
    type: "عربي / مصري",
    category: "drama",
    age: 32,
    style: "مستشارة قانونية لشركات كبرى، ذكاء حاد",
    gender: "أنثى",
    role: "مستشارة قانونية / دراما وأعمال",
    personality: "تحلل الثغرات، واثقة، تحمي مصالح موكليها",
    appearance: JSON.stringify({ face: "ملامح كلاسيكية جذابة، نظرة حاسمة", eyes: "سوداء واسعة", hair: "أسود داكن", bodyBuild: "أنيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "بدلة توكسيدو نسائية راقية", colors: "أسود، أبيض لؤلؤي" }),
    character_prompt: "Courtroom drama shot of Dina Al-Maghrabi, 32-year-old top corporate lawyer, sharp tailored suit, powerful presence",
  },
  {
    id: 21,
    name: "عادل الجابري",
    type: "عربي / خليجي",
    category: "noir",
    age: 46,
    style: "قائد عمليات خاصة وأمنية، حزم وسرعة قرار",
    gender: "ذكر",
    role: "قائد أمني / إثارة وتشويق",
    personality: "لا يعرف التردد، يقود الفرق في أصعب الظروف",
    appearance: JSON.stringify({ face: "ملامح قاسية ومهيبة، ندبة خفيفة", eyes: "بنية داكنة", hair: "محلوق الجوانب", bodyBuild: "عضلي ضخم" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة عمليات مدرعة خفيفة", colors: "أسود مطفأ، زيتي تكتيكي" }),
    character_prompt: "Tactical commander Adel Al-Jaberi, 46-year-old, armored vest, walkie talkie, helicopter background, action film still",
  },
  {
    id: 22,
    name: "ليندا حبيب",
    type: "عربي / شامي",
    category: "scifi",
    age: 26,
    style: "طيارة مسيرات وطائرات مستقبلية بدون طيار",
    gender: "أنثى",
    role: "طيارة وتقنية / خيال علمي",
    personality: "سريعة الاستجابة، تعشق التكنولوجيا",
    appearance: JSON.stringify({ face: "ملامح عصرية، نظارات AR على الجبين", eyes: "عسلية", hair: "أطراف فضية", bodyBuild: "رشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "جاكيت طيار مستقبلي مع قفازات", colors: "رمادي تيتانيوم، برتقالي نيون" }),
    character_prompt: "Futuristic drone pilot Linda Habib, 26-year-old, holographic HUD glasses on forehead, futuristic city backdrop at dusk",
  },
  {
    id: 23,
    name: "أدهم سيف",
    type: "عربي / مصري",
    category: "contemporary",
    age: 34,
    style: "مخرج سينمائي ومصور وثائقي عالمي",
    gender: "ذكر",
    role: "مخرج وفنان / إعلام وسينما",
    personality: "يرى العالم من زوايا فنية غير تقليدية",
    appearance: JSON.stringify({ face: "ملامح فنية معبرة، لحية خفيفة", eyes: "بنية عميقة", hair: "بني داكن", bodyBuild: "متوسط" }),
    wardrobe: JSON.stringify({ defaultClothing: "جاكيت سفاري مع كاميرا سينمائية", colors: "زيتي، بيج، رمادي" }),
    character_prompt: "Director Adham Seif holding professional cinema camera on film set, movie lights and diffuse smoke background",
  },
  {
    id: 24,
    name: "تالا الشامسي",
    type: "عربي / خليجي",
    category: "drama",
    age: 23,
    style: "سفيرة شابة للتغير المناخي والعمل الإنساني",
    gender: "أنثى",
    role: "ناشطة إنسانية / دراما ووثائقي",
    personality: "صادقة، مؤثرة، تلهم جيل الشباب",
    appearance: JSON.stringify({ face: "ملامح بريئة مفعمة بالأمل", eyes: "بنية لامعة", hair: "أسود حريري", bodyBuild: "شابة رشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة صوفية ناعمة صديقة للبيئة", colors: "أخضر زيتوني، ترابي، أبيض" }),
    character_prompt: "Inspiring portrait of Tala Al-Shamsi, 23-year-old youth climate advocate speaking at forum, natural cinematic daylight",
  },
  {
    id: 25,
    name: "إبراهيم كمال",
    type: "عربي / مصري",
    category: "drama",
    age: 55,
    style: "بروفيسور جامعي وباحث في علم النفس البشري",
    gender: "ذكر",
    role: "أكاديمي ومستشار / دراما وغموض",
    personality: "هادئ، يحلل الشخصيات بعمق",
    appearance: JSON.stringify({ face: "ملامح مفكر، نظارات كلاسيكية", eyes: "سوداء ذكية", hair: "رمادي كامل", bodyBuild: "وقور ومتزن" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة صوفية كلاسيكية مربعات (Tweed)", colors: "بني، كحلي، بيج" }),
    character_prompt: "Professor Ibrahim Kamal in vintage university library surrounded by books, warm study lighting, classic cinema realism",
  },
  {
    id: 26,
    name: "ريان الغامدي",
    type: "عربي / خليجي",
    category: "advertising",
    age: 22,
    style: "رحالة وصانع محتوى سياحي ومغامرات",
    gender: "ذكر",
    role: "مؤثر ومغامر / إعلانات وسياحة",
    personality: "شغوف بالاكتشاف، يعشق الجبال",
    appearance: JSON.stringify({ face: "ملامح شبابية نضرة", eyes: "بنية", hair: "أسود كثيف", bodyBuild: "رياضي مرن" }),
    wardrobe: JSON.stringify({ defaultClothing: "حقيبة ظهر جبلية مع سترة رياح", colors: "أحمر قرمزي، أسود" }),
    character_prompt: "Adventure traveler Rayan Al-Ghamdi standing on mountain cliff overlooking clouds at sunrise, dynamic photography",
  },
  {
    id: 27,
    name: "جنى الخالد",
    type: "عربي / شامي",
    category: "children",
    age: 20,
    style: "راوية قصص أطفال ورسامة شخصيات كرتونية",
    gender: "أنثى",
    role: "شخصية مرحة / عالم الأطفال والكرتون",
    personality: "مبهجة، تنشر البسمة والمرح",
    appearance: JSON.stringify({ face: "ملامح مرحة معبرة", eyes: "عسلية مشرقة", hair: "بني فاتح ضفائر", bodyBuild: "حيوية" }),
    wardrobe: JSON.stringify({ defaultClothing: "مريول رسم ممتلئ بالألوان", colors: "أصفر كناري، وردي، سماوي" }),
    character_prompt: "Children storyteller Jana Al-Khaled holding illustrated fairy-tale book, colorful fantasy background, Pixar style",
  },
  {
    id: 28,
    name: "عمر الفاروق",
    type: "عربي / تاريخي",
    category: "history",
    age: 49,
    style: "قاضٍ تاريخي وعالم فقه وحكمة في العصر الذهبي",
    gender: "ذكر",
    role: "قاضٍ وحكيم / تاريخي وقانوني",
    personality: "عادل لا يخشى في الحق لومة لائم",
    appearance: JSON.stringify({ face: "هيبة ونورانية، لحية بيضاء وقورة", eyes: "سوداء ثاقبة", hair: "مغطى بعمامة", bodyBuild: "مستقيم القامة" }),
    wardrobe: JSON.stringify({ defaultClothing: "جبة صوفية فاخرة وعمامة أندلسية", colors: "أبيض، كحلي داكن" }),
    character_prompt: "Historical drama of Chief Justice Omar Al-Farouq in Islamic Golden Age court, Moorish architecture, sunbeams, cinematic prestige",
  },
  {
    id: 29,
    name: "سلمى ناصر",
    type: "عربي / خليجي",
    category: "scifi",
    age: 30,
    style: "مهندسة روبوتات وطاقة كمية في مدينة مستقبلية",
    gender: "أنثى",
    role: "مهندسة ومخترعة / خيال علمي",
    personality: "تتحدث بلغة المستقبل، هادئة ومبتكرة",
    appearance: JSON.stringify({ face: "ملامح تقنية عصرية", eyes: "بنية براقة", hair: "أسود مستقيم", bodyBuild: "رشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "بذلة معملية بيضاء مستقبلية", colors: "أبيض تيتانيوم، رمادي معدني" }),
    character_prompt: "Portrait of Salma Nasser, 30-year-old quantum engineer, futuristic cleanroom, holographic code screens",
  },
  {
    id: 30,
    name: "ياسمين الصالح",
    type: "عربي / شامي",
    category: "drama",
    age: 37,
    style: "مؤلفة موسيقية وعازفة بيانو سيمفوني للأفلام",
    gender: "أنثى",
    role: "موسيقية وفنانة / دراما وسينما",
    personality: "حساسة، تعبر بالمشاعر الوجدانية العميقة",
    appearance: JSON.stringify({ face: "ملامح فنية رومانسية حالمة", eyes: "عسلية دافئة", hair: "كستنائي مموج", bodyBuild: "رشيقة وأنيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "فستان سهرة أسود كلاسيكي", colors: "أسود مخملي" }),
    character_prompt: "Cinematic shot of composer Yasmeen Al-Saleh sitting at grand piano on concert stage, warm spotlight, emotional drama film aesthetic",
  },
  {
    id: 31,
    name: "فارس النمري",
    type: "عربي / خليجي",
    category: "advertising",
    age: 30,
    style: "مطور عقاري وفارس خيل عربي أصيل، طابع فخم",
    gender: "ذكر",
    role: "فارس وريادي / إعلانات فاخرة",
    personality: "يرمز للشهامة والنجاح والثراء الراقي",
    appearance: JSON.stringify({ face: "ملامح عربية جذابة، لحية خفيفة أنيقة", eyes: "سوداء حادة", hair: "أسود مصفف", bodyBuild: "فارس رياضي قوي" }),
    wardrobe: JSON.stringify({ defaultClothing: "بشت أسود مذهب فوق ثوب سعودي أنيق", colors: "أسود، ذهبي، أبيض" }),
    character_prompt: "Luxury commercial shot of Faris Al-Nemari standing next to Arabian black stallion, desert sunset palace, high-end luxury brand aesthetic",
  },
];

async function run() {
  console.log("🎬 Connecting to PostgreSQL & Seeding 31 Digital Actors...");
  let successCount = 0;
  for (const a of actorsList) {
    const query = `
      INSERT INTO actors (id, name, type, category, age, style, gender, role, personality, appearance, wardrobe, character_prompt, created_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW())
      ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        type = EXCLUDED.type,
        category = EXCLUDED.category,
        age = EXCLUDED.age,
        style = EXCLUDED.style,
        gender = EXCLUDED.gender,
        role = EXCLUDED.role,
        personality = EXCLUDED.personality,
        appearance = EXCLUDED.appearance,
        wardrobe = EXCLUDED.wardrobe,
        character_prompt = EXCLUDED.character_prompt;
    `;
    const values = [a.id, a.name, a.type, a.category, a.age, a.style, a.gender, a.role, a.personality, a.appearance, a.wardrobe, a.character_prompt];
    try {
      await pool.query(query, values);
      successCount++;
    } catch (err) {
      console.error(`❌ Failed on actor #${a.id} (${a.name}):`, err.message);
    }
  }
  console.log(`\n🎉 Success! Seeded ${successCount} / 31 Digital Actors into Database!`);
  await pool.end();
  process.exit(0);
}

run().catch((err) => {
  console.error("Critical error:", err);
  process.exit(1);
});
