import { Router, type IRouter } from "express";
import healthRouter from "./health";
import actorsRouter from "./actors";
import worldsRouter from "./worlds";
import projectsRouter from "./projects";
import scriptsRouter from "./scripts";
import shotsRouter from "./shots";
import tasksRouter from "./tasks";
import clipsRouter from "./clips";
import studioRouter from "./studio";
import videoRouter from "./video";
import voiceRouter from "./voice";
import audioRouter from "./audio";
import bibleRouter from "./bible";
import timelineRouter from "./timeline";
import subtitlesRouter from "./subtitles";
import pipelineRouter from "./pipeline";
import renderRouter from "./render";
import productionRouter from "./production";

const router: IRouter = Router();

router.use(healthRouter);
router.use(actorsRouter);
router.use(worldsRouter);
router.use("/projects", projectsRouter);
router.use(scriptsRouter);
router.use(shotsRouter);
router.use(tasksRouter);
router.use(clipsRouter);
router.use(studioRouter);
router.use("/video", videoRouter);
router.use(voiceRouter);
router.use(audioRouter);
router.use(bibleRouter);
router.use(timelineRouter);
router.use(subtitlesRouter);
router.use("/pipeline", pipelineRouter);
router.use("/render", renderRouter);
router.use(productionRouter);

export default router;
