import { db, actorsTable } from "@workspace/db";

const actorsList = [
  {
    id: 1,
    name: "طارق المنصور",
    type: "عربي / خليجي",
    category: "drama",
    age: 38,
    style: "قيادي، حازم، نبرة صوت عميقة، كاريزما سينمائية قوية",
    gender: "ذكر",
    role: "بطل رئيسي / قائد استراتيجي",
    personality: "هادئ، ذكي، صارم في قراراته، يمتلك بعد نظر استراتيجي",
    appearance: JSON.stringify({ face: "ملامح عربية حادة، لحية كلاسيكية مشذبة", eyes: "بنية داكنة", hair: "أسود قصير", bodyBuild: "بنية رياضية متناسقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "بدلة رسمية داكنة بدون ربطة عنق / عباءة فاخرة", colors: "كحلي، رمادي داكن، أسود" }),
    characterPrompt: "Cinematic portrait of Tariq Al-Mansoor, 38-year-old Arab leader, sharp features, well-groomed beard, sharp dark eyes, wearing a tailored charcoal suit, dramatic cinematic lighting, 8k photorealistic",
  },
  {
    id: 2,
    name: "سارة الأحمد",
    type: "عربي / شامي",
    category: "contemporary",
    age: 31,
    style: "واثقة، سريعة البديهة، أسلوب قانوني واستقصائي راقٍ",
    gender: "أنثى",
    role: "بطلة رئيسية / محامية وصحفية",
    personality: "شجاعة، فضولية، تبحث عن الحقيقة وتواجه التحديات",
    appearance: JSON.stringify({ face: "ملامح ناعمة لكن واثقة، نظرات ثاقبة", eyes: "عسلية", hair: "كستنائي مائل للطول", bodyBuild: "رشيقة وأنيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة بليزر عصرية، قميص أبيض حريري", colors: "عاجي، كحلي، عنابي" }),
    characterPrompt: "Cinematic portrait of Sarah Al-Ahmad, 31-year-old Arab professional woman, hazel eyes, elegant chestnut hair, wearing a stylish navy blazer, intense and intelligent expression, high production lighting",
  },
  {
    id: 3,
    name: "يوسف النجار",
    type: "عربي / مصري",
    category: "noir",
    age: 44,
    style: "محقق جنائي غامض، عميق التفكير، نبرة هادئة وساخرة",
    gender: "ذكر",
    role: "محقق جنائي / خبير غموض",
    personality: "ملاحظ دقيق للتفاصيل، لا يثق بسهولة، يعتمد على المنطق البحت",
    appearance: JSON.stringify({ face: "ملامح ناضجة تحمل تجارب السنين، شوارب خفيفة", eyes: "سوداء ثاقبة", hair: "أسود يتخلله شيب وقور", bodyBuild: "طويل القامة، بنية متوسطة" }),
    wardrobe: JSON.stringify({ defaultClothing: "معطف جلدي طويل، قبعة فيدورا كلاسيكية", colors: "بني محروق، رمادي دخاني" }),
    characterPrompt: "Cinematic film-noir still of Yousef Al-Najjar, 44-year-old veteran detective, mature face with salt-and-pepper hair, intense gaze, trench coat, foggy alleyway lighting, volumetric shadows",
  },
  {
    id: 4,
    name: "ليلى الشامي",
    type: "عربي / شامي",
    category: "scifi",
    age: 28,
    style: "عالمة ذكاء اصطناعي وباحثة مستقبلية، ذكاء متقد",
    gender: "أنثى",
    role: "عالمة ومخترعة / خيال علمي",
    personality: "منهجية، دقيقة، تسعى لحل ألغاز التكنولوجيا المتقدمة",
    appearance: JSON.stringify({ face: "بشرة نضرة، ملامح معاصرة", eyes: "خضراء مائلة للعسلي", hair: "أسود قصير وعصري", bodyBuild: "رياضية رشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة سايبربانك تقنية خفيفة مع ألياف ضوئية", colors: "فضي معدني، أزرق نيون، أبيض" }),
    characterPrompt: "Portrait of Layla Al-Shami, 28-year-old Arabic tech scientist, subtle glowing cyber elements on collar, short black hair, clean sci-fi laboratory background, futuristic cinematic tone",
  },
  {
    id: 5,
    name: "خالد العمري",
    type: "عربي / تاريخي",
    category: "history",
    age: 42,
    style: "فارس وقائد تاريخي، شجاعة منقطعة النظير، صوت جهوري",
    gender: "ذكر",
    role: "قائد فرسان / تاريخي وملحمي",
    personality: "نبيل، مخلص لعهده، حازم في المعارك ورحيم مع الضعفاء",
    appearance: JSON.stringify({ face: "بشرة سمراء لوحتها الشمس، عيون صقرية، لحية كاملة", eyes: "بنية", hair: "طويل ملموم للخلف", bodyBuild: "بنية عضلية قوية وفارعة" }),
    wardrobe: JSON.stringify({ defaultClothing: "درع جلدي مزخرف بصفائح نحاسية، عباءة صوفية", colors: "ترابي، برونزي، أحمر داكن" }),
    characterPrompt: "Cinematic epic shot of Khalid Al-Omari, 42-year-old ancient Arab warrior commander, leather and bronze armor, fierce determined eyes, golden hour desert lighting, masterpiece film quality",
  },
  {
    id: 6,
    name: "مريم القحطاني",
    type: "عربي / خليجي",
    category: "history",
    age: 29,
    style: "عالمة آثار ومستكشفة حضارات قديمة",
    gender: "أنثى",
    role: "مستكشفة ومؤرخة / مغامرات",
    personality: "عاشقة للتراث والتاريخ، جريئة في الميدان والاستكشاف",
    appearance: JSON.stringify({ face: "ملامح عربية أصيلة، ابتسامة واثقة", eyes: "بنية واسعة", hair: "طويل مضفور", bodyBuild: "رياضية ميدانية" }),
    wardrobe: JSON.stringify({ defaultClothing: "زي استكشاف ميداني صحراوي، وشاح كتان", colors: "كاكي، بيج، بني" }),
    characterPrompt: "Cinematic portrait of Maryam Al-Qahtani, 29-year-old archaeologist explorer in desert ruins, linen scarf, dust particles in sunbeam, adventure movie aesthetic",
  },
  {
    id: 7,
    name: "كريم عبد الله",
    type: "عربي / مصري",
    category: "advertising",
    age: 26,
    style: "شاب عصري حيوي، مبتسم، كاريزما إعلانية وتجارية",
    gender: "ذكر",
    role: "واجهة إعلانية / ريادي أعمال",
    personality: "مرح، متفائل، متحدث لبق ومقنع",
    appearance: JSON.stringify({ face: "ملامح وسيمة وشابة، ابتسامة ناصعة", eyes: "عسلية", hair: "بني مموج أنيق", bodyBuild: "شاب رشيق" }),
    wardrobe: JSON.stringify({ defaultClothing: "تيشيرت عصري وقميص كتان مفتوح", colors: "أبيض، كحلي، زيتوني" }),
    characterPrompt: "Commercial high-end portrait of Kareem Abdullah, 26-year-old charismatic Arab entrepreneur, radiant natural smile, bright studio commercial lighting, premium aesthetic",
  },
  {
    id: 8,
    name: "نورا الزهراني",
    type: "عربي / خليجي",
    category: "drama",
    age: 35,
    style: "سيدة أعمال ومفاوضة دبلوماسية، أناقة متناهية",
    gender: "أنثى",
    role: "شخصية نافذة / دراما اجتماعية",
    personality: "هادئة، حكيمة، تمتلك مهارات قيادية واجتماعية رفيعة",
    appearance: JSON.stringify({ face: "ملامح ملكية راقية، نظرات هادئة", eyes: "بنية داكنة", hair: "أسود ناعم مسدول", bodyBuild: "قوام ممشوق" }),
    wardrobe: JSON.stringify({ defaultClothing: "عباءة مخملية مطرزة بالحرير / فستان رسمي", colors: "زمردي، أسود، ذهبي مطفأ" }),
    characterPrompt: "Cinematic portrait of Noura Al-Zahrani, 35-year-old elegant Arab businesswoman, emerald green couture abaya, soft luxury cinematic lighting, high-end drama film still",
  },
  {
    id: 9,
    name: "زياد الشريف",
    type: "عربي / شامي",
    category: "noir",
    age: 33,
    style: "عميل استخباراتي وطيار سابق، سريع الحركة وردود الفعل",
    gender: "ذكر",
    role: "بطل أكشن / تشويق وجريمة",
    personality: "صارم، قليل الكلام، ينفذ المهام المعقدة بدقة متناهية",
    appearance: JSON.stringify({ face: "فكان بارزان، نظرة حادة وثاقبة", eyes: "رمادية مائلة للبني", hair: "أسود قصير عسكري", bodyBuild: "بنية قتالية قوية" }),
    wardrobe: JSON.stringify({ defaultClothing: "جاكيت بومبر جلدي تكتيكي، قفازات بدون أصابع", colors: "أسود كربوني، رمادي خرساني" }),
    characterPrompt: "Cinematic action shot of Ziad Al-Sharif, 33-year-old operative, tactical jacket, intense focus, rain and city lights bokeh background, 8k resolution",
  },
  {
    id: 10,
    name: "ريم البلوشي",
    type: "عربي / خليجي",
    category: "contemporary",
    age: 27,
    style: "صحفية استقصائية جريئة ومقدمة بودكاست وثائقي",
    gender: "أنثى",
    role: "إعلامية وباحثة / دراما ومعاصر",
    personality: "عنيدة في ملاحقة الحقيقة، ذكية وتكشف التفاصيل الخفية",
    appearance: JSON.stringify({ face: "ملامح شبابية معبرة، عيون فضولية", eyes: "بنية لامعة", hair: "أسود متوسط الطول", bodyBuild: "طبيعية ورشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة جينز عصرية، سماعات احترافية حول الرقبة", colors: "كحلي، خردلي، أبيض" }),
    characterPrompt: "Cinematic documentary still of Reem Al-Balushi, 27-year-old investigative journalist holding recorder, urban background, realistic lighting, Netflix documentary style",
  },
  {
    id: 11,
    name: "ماجد التميمي",
    type: "عربي / خليجي",
    category: "scifi",
    age: 36,
    style: "قائد محطة فضاء ومستكشف عوالم جديدة",
    gender: "ذكر",
    role: "قائد فضاء / خيال علمي",
    personality: "منضبط، شجاع، قادر على اتخاذ قرارات مصيرية في الأزمات",
    appearance: JSON.stringify({ face: "ملامح صارمة وهادئة في الفضاء", eyes: "عسلية غامقة", hair: "أسود قصير جداً", bodyBuild: "قوي متمرس" }),
    wardrobe: JSON.stringify({ defaultClothing: "بذلة رواد فضاء بيضاء مزينة بالشارات العربية", colors: "أبيض ناصع، رمادي، لمسات ذهبية" }),
    characterPrompt: "Cinematic space movie still of Majed Al-Tamimi, 36-year-old Arab astronaut commander in high-tech spacesuit, Earth reflection on visor, Interstellar aesthetic",
  },
  {
    id: 12,
    name: "فاطمة الدوسري",
    type: "عربي / خليجي",
    category: "drama",
    age: 40,
    style: "طبيبة جراحة ورئيسة قسم طبي إنساني",
    gender: "أنثى",
    role: "طبيبة وقيادية / دراما إنسانية",
    personality: "حنونة، مخلصة لمهنتها، قوية تحت الضغوط القصوى",
    appearance: JSON.stringify({ face: "ملامح ناضجة ومريحة تبعث على الاطمئنان", eyes: "بنية دافئة", hair: "مغطى بغطاء طبي أنيق", bodyBuild: "معتدلة" }),
    wardrobe: JSON.stringify({ defaultClothing: "معطف طبي أبيض ناصع فوق ملابس العمليات", colors: "أبيض، أزرق سماوي" }),
    characterPrompt: "Cinematic hospital drama portrait of Dr. Fatima Al-Dosari, 40-year-old surgeon, stethoscope around neck, warm compassionate gaze, soft cinematic hospital lighting",
  },
  {
    id: 13,
    name: "حمزة إدريس",
    type: "عربي / مغاربي",
    category: "advertising",
    age: 25,
    style: "بطل رياضي ومدرب لياقة، طاقة إيجابية متفجرة",
    gender: "ذكر",
    role: "رياضي وواجهة تسويقية / إعلانات",
    personality: "ملهم، نشيط، يشجع الجميع على التحدي والنجاح",
    appearance: JSON.stringify({ face: "ملامح رياضية منحوتة، ابتسامة عريضة", eyes: "بنية", hair: "مجعد قصير ومحدد", bodyBuild: "عضلات مفتولة وقوام رياضي" }),
    wardrobe: JSON.stringify({ defaultClothing: "ملابس رياضية تقنية عالية الجودة", colors: "أسود، برتقالي ناري" }),
    characterPrompt: "High-energy commercial shot of Hamza Idriss, 25-year-old Arab athlete running in modern city, motion blur, sunrise lighting, Nike commercial cinematic quality",
  },
  {
    id: 14,
    name: "هدى السعيد",
    type: "عربي / شامي",
    category: "drama",
    age: 48,
    style: "دبلوماسية وأستاذة علاقات دولية، وقار وحكمة بالغة",
    gender: "أنثى",
    role: "سفيرة ودبلوماسية / دراما سياسية",
    personality: "دقيقة في اختيار الكلمات، بارعة في التفاوض وحل النزاعات",
    appearance: JSON.stringify({ face: "وقار ونضج، نظارات طبية أنيقة بإطار ذهبي", eyes: "عسلية داكنة", hair: "رمادي وفضي منسق بعناية", bodyBuild: "أنيقة ورزينة" }),
    wardrobe: JSON.stringify({ defaultClothing: "بدلة رسمية كلاسيكية مع وشاح حريري", colors: "كحلي ملكي، عنابي داكن" }),
    characterPrompt: "Portrait of Huda Al-Saeed, 48-year-old seasoned diplomat, tailored dark royal blue suit, thoughtful dignified gaze, international summit background, cinematic realism",
  },
  {
    id: 15,
    name: "بدر المطيري",
    type: "عربي / خليجي",
    category: "history",
    age: 50,
    style: "نوخذة وقبطان بحري تراثي، خبير في أسرار البحار والنجوم",
    gender: "ذكر",
    role: "قبطان ومستكشف بحري / تاريخي وتراثي",
    personality: "حكيم، صبور، يحفظ خرائط الرياح والنجوم عن ظهر قلب",
    appearance: JSON.stringify({ face: "تجاعيد وقورة رسمها ملح البحر والرياح، لحية بيضاء", eyes: "بنية عميقة", hair: "أبيض", bodyBuild: "قوي متمرس على أهوال البحر" }),
    wardrobe: JSON.stringify({ defaultClothing: "دشداشة تقليدية وغترة بيضاء، شال صوف", colors: "أبيض، بيج رملي" }),
    characterPrompt: "Cinematic portrait of Captain Bader Al-Mutairi, 50-year-old Arab sea captain on traditional wooden dhow ship, sea breeze, sunset golden hour lighting, national geographic film style",
  },
  {
    id: 16,
    name: "شهد العتيبي",
    type: "عربي / خليجي",
    category: "contemporary",
    age: 24,
    style: "مهندسة معمارية شابة ورائدة في المباني المستدامة",
    gender: "أنثى",
    role: "مهندسة ومصممة / معاصر وإعلانات",
    personality: "مبتكرة، طموحة، تجمع بين الأصالة العمرانية والتقنية الحديثة",
    appearance: JSON.stringify({ face: "ابتسامة ملهمة وملامح طفولية ذكية", eyes: "سوداء واسعة", hair: "أسود ناعم", bodyBuild: "رشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "خوذة مهندس بيضاء، سترة عصرية مع مخططات هندسية", colors: "أبيض، رمادي فاتح، أصفر مهني" }),
    characterPrompt: "Cinematic shot of Shahad Al-Otaibi, 24-year-old female architect holding blueprint overlooking modern futuristic skyline, morning light, inspiring and cinematic",
  },
  {
    id: 17,
    name: "سامي حداد",
    type: "عربي / شامي",
    category: "noir",
    age: 39,
    style: "خبير أدلة جنائية وتحليل مسرح الجريمة",
    gender: "ذكر",
    role: "محلل جنائي / غموض وتحقيق",
    personality: "مهووس بالحقائق العلمية، دقيق لدرجة الميكروسكوب",
    appearance: JSON.stringify({ face: "ملامح مركزة، نظارات بدون إطار", eyes: "بنية فاتحة", hair: "بني قصير", bodyBuild: "نحيل ودقيق" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة مختبر رمادية مع قفازات فحص مطاطية", colors: "رمادي، كحلي" }),
    characterPrompt: "Forensic investigator Sami Haddad analyzing glowing evidence in dark forensics lab, blue ultraviolet accent lighting, crime thriller aesthetic, 8k",
  },
  {
    id: 18,
    name: "دانة العلي",
    type: "عربي / خليجي",
    category: "advertising",
    age: 29,
    style: "مقدمة برامج تلفزيونية وإعلامية متألقة",
    gender: "أنثى",
    role: "مذيعة وإعلامية / دعاية وإعلام",
    personality: "فصيحة اللسان، لبقة، تجذب الجمهور بحضورها الطاغي",
    appearance: JSON.stringify({ face: "ملامح إعلامية جذابة ومشرقة", eyes: "عسلية براقة", hair: "كستنائي مموج", bodyBuild: "أنيقة جداً" }),
    wardrobe: JSON.stringify({ defaultClothing: "فستان كوكتيل رسمي راقٍ للمؤتمرات", colors: "أزرق نيلي، وردي هادئ" }),
    characterPrompt: "Studio portrait of Dana Al-Ali, 29-year-old TV anchorwoman, holding microphone, professional broadcast studio lights, glamorous cinematic look",
  },
  {
    id: 19,
    name: "وليد الصبان",
    type: "عربي / مغاربي",
    category: "history",
    age: 62,
    style: "حكيم القرية وراوي الأساطير الشعبية",
    gender: "ذكر",
    role: "حكيم وراوٍ / قصص وروايات وفانتازيا",
    personality: "هادئ، صوته رخيم يروي القصص بأسلوب يأسر الألباب",
    appearance: JSON.stringify({ face: "وجه منير ممتلئ بالحكمة والسكينة، لحية بيضاء طويلة", eyes: "بنية حنونة", hair: "أبيض كامل", bodyBuild: "مهيب" }),
    wardrobe: JSON.stringify({ defaultClothing: "قفطان مغربي أصيل وعمامة تقليدية", colors: "أبيض عاجي، بيج صوفي" }),
    characterPrompt: "Cinematic portrait of Walid Al-Sabban, 62-year-old wise storyteller around fireplace, warm amber glow on white beard and robes, Arabian Nights storytelling atmosphere",
  },
  {
    id: 20,
    name: "دينا المغربي",
    type: "عربي / مصري",
    category: "drama",
    age: 32,
    style: "مستشارة قانونية لشركات كبرى، ذكاء حاد وحضور قوي",
    gender: "أنثى",
    role: "مستشارة قانونية / دراما وأعمال",
    personality: "تحلل الثغرات، واثقة، تحمي مصالح موكليها ببراعة",
    appearance: JSON.stringify({ face: "ملامح مصرية كلاسيكية جذابة، نظرة حاسمة", eyes: "سوداء واسعة", hair: "أسود داكن مصفف", bodyBuild: "أنيقة وممشوقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "بدلة توكسيدو نسائية راقية", colors: "أسود، أبيض لؤلؤي" }),
    characterPrompt: "Cinematic courtroom drama shot of Dina Al-Maghrabi, 32-year-old top corporate lawyer, sharp tailored suit, confident powerful presence, cinematic lens",
  },
  {
    id: 21,
    name: "عادل الجابري",
    type: "عربي / خليجي",
    category: "noir",
    age: 46,
    style: "قائد عمليات خاصة وأمنية، حزم وسرعة قرار",
    gender: "ذكر",
    role: "قائد أمني / إثارة وتشويق",
    personality: "لا يعرف التردد، يقود الفرق الميدانية في أصعب الظروف",
    appearance: JSON.stringify({ face: "ملامح قاسية ومهيبة، ندبة خفيفة على الحاجب", eyes: "بنية داكنة", hair: "محلوق على الجوانب", bodyBuild: "عضلي ضخم" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة عمليات مدرعة خفيفة مع شارات قيادة", colors: "أسود مطفأ، زيتي تكتيكي" }),
    characterPrompt: "Cinematic tactical commander Adel Al-Jaberi, 46-year-old, armored vest, walkie talkie on shoulder, helicopter in background, action film still",
  },
  {
    id: 22,
    name: "ليندا حبيب",
    type: "عربي / شامي",
    category: "scifi",
    age: 26,
    style: "طيارة مسيرات وطائرات بدون طيار في المدن المستقبلية",
    gender: "أنثى",
    role: "طيارة وتقنية / خيال علمي",
    personality: "سريعة الاستجابة، تعشق السرعة وتتحكم في أسراب الروبوتات",
    appearance: JSON.stringify({ face: "ملامح عصرية شابة، نظارات الواقع المعزز AR على الجبين", eyes: "عسلية", hair: "مصبوغ بأطراف فضية خفيفة", bodyBuild: "رشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "جاكيت طيار مستقبلي مع قفازات هولوغرافية", colors: "رمادي تيتانيوم، برتقالي نيون" }),
    characterPrompt: "Futuristic drone pilot Linda Habib, 26-year-old, holographic HUD glasses resting on forehead, futuristic city backdrop at dusk, cyberpunk cinematic tone",
  },
  {
    id: 23,
    name: "أدهم سيف",
    type: "عربي / مصري",
    category: "contemporary",
    age: 34,
    style: "مخرج سينمائي ومصور وثائقي عالمي",
    gender: "ذكر",
    role: "مخرج وفنان / إعلام وسينما",
    personality: "يرى العالم من زوايا فنية غير تقليدية، شغوف بالتعبير الإنساني",
    appearance: JSON.stringify({ face: "ملامح فنية معبرة، لحية خفيفة عصرية", eyes: "بنية عميقة", hair: "بني داكن", bodyBuild: "متوسط" }),
    wardrobe: JSON.stringify({ defaultClothing: "جاكيت سفاري للمصورين مع كاميرا سينمائية احترافية", colors: "زيتي، بيج، رمادي" }),
    characterPrompt: "Cinematic director Adham Seif holding professional cinema camera on film set, movie lights and diffuse smoke in background, filmmaking documentary aesthetic",
  },
  {
    id: 24,
    name: "تالا الشامسي",
    type: "عربي / خليجي",
    category: "drama",
    age: 23,
    style: "سفيرة شابة للتغير المناخي والعمل الإنساني",
    gender: "أنثى",
    role: "ناشطة إنسانية / دراما ووثائقي",
    personality: "صادقة، مؤثرة، تلهم جيل الشباب للدفاع عن الكوكب",
    appearance: JSON.stringify({ face: "ملامح بريئة مفعمة بالأمل والحيوية", eyes: "بنية واسعة ولامعة", hair: "أسود حريري", bodyBuild: "شابة رشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة صوفية ناعمة صديقة للبيئة", colors: "أخضر زيتوني، ترابي، أبيض" }),
    characterPrompt: "Inspiring cinematic portrait of Tala Al-Shamsi, 23-year-old youth climate advocate speaking at international forum, natural cinematic daylight",
  },
  {
    id: 25,
    name: "إبراهيم كمال",
    type: "عربي / مصري",
    category: "drama",
    age: 55,
    style: "بروفيسور جامعي وباحث في علم النفس والسلوك البشري",
    gender: "ذكر",
    role: "أكاديمي ومستشار / دراما وغموض",
    personality: "هادئ جداً، يحلل الشخصيات من نبرة صوتهم وحركاتهم",
    appearance: JSON.stringify({ face: "ملامح مفكر متأمل، نظارات كلاسيكية سميكة", eyes: "سوداء ذكية", hair: "رمادي كامل", bodyBuild: "وقور ومتزن" }),
    wardrobe: JSON.stringify({ defaultClothing: "سترة صوفية كلاسيكية مربعات (Tweed Jacket)", colors: "بني، كحلي، بيج" }),
    characterPrompt: "Distinguished academic Professor Ibrahim Kamal in vintage university library surrounded by antique books, warm study lighting, classic cinema realism",
  },
  {
    id: 26,
    name: "ريان الغامدي",
    type: "عربي / خليجي",
    category: "advertising",
    age: 22,
    style: "رحالة وصانع محتوى سياحي، مغامرات شيقة",
    gender: "ذكر",
    role: "مؤثر ومغامر / إعلانات وسياحة",
    personality: "شغوف بالاكتشاف، يبتسم دائماً ويعشق تسلق الجبال",
    appearance: JSON.stringify({ face: "ملامح شبابية نضرة، ابتسامة عفوية", eyes: "بنية", hair: "أسود كثيف", bodyBuild: "رياضي مرن" }),
    wardrobe: JSON.stringify({ defaultClothing: "حقيبة ظهر للمشي الجبلي مع سترة مقاومة للرياح", colors: "أحمر قرمزي، أسود" }),
    characterPrompt: "Adventure traveler Rayan Al-Ghamdi standing on mountain cliff overlooking clouds at sunrise, wind jacket, dynamic photography, GoPro / Red camera cinematic still",
  },
  {
    id: 27,
    name: "جنى الخالد",
    type: "عربي / شامي",
    category: "children",
    age: 20,
    style: "راوية قصص أطفال ورسامة شخصيات كرتونية",
    gender: "أنثى",
    role: "شخصية مرحة / عالم الأطفال والكرتون",
    personality: "مبهجة، تحب الألوان ورسم البسمة على وجوه الأطفال",
    appearance: JSON.stringify({ face: "ملامح مرحة معبرة وابتسامة طفولية لطيفة", eyes: "عسلية مشرقة", hair: "بني فاتح ضفائر", bodyBuild: "حيوية" }),
    wardrobe: JSON.stringify({ defaultClothing: "مريول رسم ممتلئ بالألوان المبهجة", colors: "أصفر كناري، وردي، سماوي" }),
    characterPrompt: "Whimsical children storyteller Jana Al-Khaled holding illustrated fairy-tale book, colorful animated fantasy background, Disney Pixar inspired warm realism",
  },
  {
    id: 28,
    name: "عمر الفاروق",
    type: "عربي / تاريخي",
    category: "history",
    age: 49,
    style: "قاضٍ تاريخي وعالم فقه وحكمة في العصور الذهبية",
    gender: "ذكر",
    role: "قاضٍ وحكيم / تاريخي وقانوني",
    personality: "عادل لا يخشى في الحق لومة لائم، وقور الكلمة",
    appearance: JSON.stringify({ face: "هيبة ونورانية في الوجه، لحية بيضاء مخضبة بالوقار", eyes: "سوداء ثاقبة", hair: "مغطى بعمامة إسلامية تاريخية", bodyBuild: "مستقيم القامة" }),
    wardrobe: JSON.stringify({ defaultClothing: "جبة صوفية فاخرة مطرزة بالحرير وعمامة أندلسية", colors: "أبيض، كحلي داكن" }),
    characterPrompt: "Historical drama scene of Chief Justice Omar Al-Farouq in Islamic Golden Age court, ornate Moorish architecture, sunbeams through geometric windows, cinematic prestige",
  },
  {
    id: 29,
    name: "سلمى ناصر",
    type: "عربي / خليجي",
    category: "scifi",
    age: 30,
    style: "مهندسة روبوتات وطاقة كمية في مدينة نيوم المستقبلية",
    gender: "أنثى",
    role: "مهندسة ومخترعة / خيال علمي",
    personality: "تتحدث بلغة المستقبل، هادئة وترى الحلول قبل حدوث المشاكل",
    appearance: JSON.stringify({ face: "ملامح تقنية عصرية أنيقة", eyes: "بنية براقة", hair: "أسود مستقيم قصير", bodyBuild: "رشيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "بذلة معملية بيضاء عصرية خالية من الأزرار", colors: "أبيض تيتانيوم، رمادي معدني" }),
    characterPrompt: "Cinematic portrait of Salma Nasser, 30-year-old quantum robotics engineer in futuristic cleanroom, glass screens with Arabic holographic code, futuristic lighting",
  },
  {
    id: 30,
    name: "ياسمين الصالح",
    type: "عربي / شامي",
    category: "drama",
    age: 37,
    style: "مؤلفة موسيقية وعازفة بيانو سيمفوني للأفلام",
    gender: "أنثى",
    role: "موسيقية وفنانة / دراما وسينما",
    personality: "حساسة، تعبر بالنغمات والمشاعر الوجدانية العميقة",
    appearance: JSON.stringify({ face: "ملامح فنية رومانسية حالمة", eyes: "عسلية دافئة", hair: "كستنائي مموج طويل", bodyBuild: "رشيقة وأنيقة" }),
    wardrobe: JSON.stringify({ defaultClothing: "فستان سهرة أسود كلاسيكي لعازفات الأوركسترا", colors: "أسود مخملي" }),
    characterPrompt: "Cinematic shot of composer Yasmeen Al-Saleh sitting at grand piano on concert stage, warm spotlight, dust motes dancing in light, emotional drama film aesthetic",
  },
  {
    id: 31,
    name: "فارس النمري",
    type: "عربي / خليجي",
    category: "advertising",
    age: 30,
    style: "مطور عقاري وفارس خيل عربي أصيل، طابع فخم",
    gender: "ذكر",
    role: "فارس وريادي / إعلانات فاخرة",
    personality: "يرمز للشهامة والنجاح والثراء الراقي",
    appearance: JSON.stringify({ face: "ملامح عربية جذابة ولحية خفيفة أنيقة", eyes: "سوداء حادة", hair: "أسود مصفف", bodyBuild: "فارس رياضي قوي" }),
    wardrobe: JSON.stringify({ defaultClothing: "بشت أسود مذهب فوق ثوب سعودي أنيق / زي فروسية إنجليزي", colors: "أسود، ذهبي، أبيض" }),
    characterPrompt: "Luxury commercial shot of Faris Al-Nemari standing next to a magnificent Arabian black stallion, desert sunset palace background, high-end luxury brand aesthetic",
  },
];

async function seed() {
  console.log("🎬 Starting injection of 31 Official Digital Actors for Kayan AI Productions...");
  let count = 0;
  for (const actor of actorsList) {
    try {
      await db
        .insert(actorsTable)
        .values({
          id: actor.id,
          name: actor.name,
          type: actor.type,
          category: actor.category,
          age: actor.age,
          style: actor.style,
          gender: actor.gender,
          role: actor.role,
          personality: actor.personality,
          appearance: actor.appearance,
          wardrobe: actor.wardrobe,
          characterPrompt: actor.characterPrompt,
          createdAt: new Date(),
        })
        .onConflictDoUpdate({
          target: actorsTable.id,
          set: {
            name: actor.name,
            type: actor.type,
            category: actor.category,
            age: actor.age,
            style: actor.style,
            gender: actor.gender,
            role: actor.role,
            personality: actor.personality,
            appearance: actor.appearance,
            wardrobe: actor.wardrobe,
            characterPrompt: actor.characterPrompt,
          },
        });
      count++;
    } catch (e: any) {
      console.error(`Error seeding actor ${actor.name}:`, e.message);
    }
  }
  console.log(`✅ Successfully seeded and synchronized ${count} / 31 Digital Actors into PostgreSQL database.`);
  process.exit(0);
}

seed();
