import { pgTable, serial, text, integer, timestamp } from "drizzle-orm/pg-core";

export const actorsTable = pgTable("actors", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  type: text("type").notNull(),
  category: text("category").notNull().default("global"),
  age: integer("age").notNull(),
  style: text("style").notNull(),
  imageUrl: text("image_url"),
  
  // المجموعة الأولى من الأعمدة المخزنة في السيرفر
  eye_color: text("eye_color"),
  hair_style: text("hair_style"),
  physical_description: text("physical_description"),
  personality_traits: text("personality_traits"),
  backstory: text("backstory"),
  clothing_prompt: text("clothing_prompt"),
  character_master_prompt: text("character_master_prompt"),
  character_negative_prompt: text("character_negative_prompt"),
  face_reference_url: text("face_reference_url"),
  body_reference_url: text("body_reference_url"),
  secondary_reference_url: text("secondary_reference_url"),
  voice_provider: text("voice_provider"),
  face_description: text("face_description"),
  hair: text("hair"),
  eyes: text("eyes"),
  clothing: text("clothing"),
  distinctive_features: text("distinctive_features"),
  psychological_traits: text("psychological_traits"),
  speech_style: text("speech_style"),
  voice: text("voice"),

  // المجموعة الثانية من الأعمدة المخزنة في السيرفر (مصححة)
  gender: text("gender"),
  voice_id: text("voice_id"),
  background: text("background"),
  reference_images: text("reference_images"),
  character_prompt: text("character_prompt"),
  negative_prompt: text("negative_prompt"),
  role: text("role"),
  personality: text("personality"),
  behavior: text("behavior"),
  speaking_style: text("speaking_style"),
  appearance: text("appearance"),
  wardrobe: text("wardrobe"),
  voice_settings: text("voice_settings"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
